Cargo.toml
examples/include.rs
examples/spirv.rs

Fixes the following on 0.5.4:
error[E0308]: mismatched types
--> /home/marijn/.cargo/registry/src/github.com-1ecc6299db9ec823/rspirv-0.5.4/mr/constructs.rs:190:22
|
190 |             version: (spirv::MAJOR_VERSION << 16) | (spirv::MINOR_VERSION << 8),
|                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found `u8`
Also fix line endings from CRLF -> LF in examples/include.rs.

rspirv: Update to 0.6.0

---

.github/dependabot.yml

Use dependabot to notify us about dependency updates.

GitHub: Add dependabot configuration for update notifications

---

Cargo.toml
examples/intellisense-tu.rs
src/intellisense/wrapper.rs
src/os.rs
src/utils.rs
src/wrapper.rs

After a look at current code with @DBouma we decided that taking references to ComPtrs is ever so slightly more natural. More importantly DXC returns objects with their refcount already incremented (detached from an internal ComPtr by taking the pointer out without decreasing the refcount). To ensure adequate cleanup it is convenient if these pointers can't be left lingering around by accident.
Simplify conversion loops and in particular pointer magic in `get_children` to shove a raw pointer into a `ComPtr`, which com_rs was not designed for. The returned pointer

Fix error source; free leaked allocations; fix refcounting; BSTR is wide, not UTF-8; convert return_hr to expression

---

examples/file-ast.rs
examples/intellisense-tu.rs
src/utils.rs
src/wrapper.rs

Depending on the platform/usecase the dlls/so's might not be available in PWD nor is it feasible for the application to change PWD on the fly. This does bloat the interface some but I don't feel like a static global and `hassle_rs::set_library_path()`  are all that pretty either.

Add optional path/directory argument for DXC/DXIL library

---

src/utils.rs

DXC (all the Windows string types using WCHAR under the hood, really) require wide strings to be terminated with a NUL character. If not, they'd use a BSTR that has a sneaky length prefix (#11), otherwise the length or ending of the string is unknown.
This has not caused any trouble before because into_vec performs the exact same conversion as into_vec_with_nul, *except* that it pops off the last character before returning the Vec. Only the size of it is reduced, the underlying memory is not reallocated and the final NUL byte is left in place.  However, in the event that a vector is shuffled around or modified we cannot permit ourselves to loose that trailing NUL.

utils: Do not strip trailing nul from wide strings

---

src/os.rs
src/utils.rs

I keep forgetting to submit this change, which would cause segfaults in the long run when newer `libdxcompiler.so` builds are used (in conjunction with intellisense only, if that makes it any better...).
We [recently](https://github.com/Traverse-Research/hassle-rs/pull/10) fixed memory leaks when calling into the intellisense part of DXC and made the decision shortly after merging to [implement null-invariant `BSTR`s properly](https://github.com/microsoft/DirectXShaderCompiler/pull/3250) in DXC's shimmed type for non-Windows, which was promptly accepted.
Currently our implementation of `SysFreeString` together with that PR segfaults because it frees the pointer at offset `+4` of the allocation. That is corrected together with `SysStringLen` now reading the size of the string from this …

Linux: Update to DXC's null-invariant BSTR

---

README.md
release.toml

`cargo release` did not bump the version in `RELEASE.md`, this configuration takes care of it. Furthermore links to PR commits in DXC got outdated and have been updated, and the inter-dependency between newer DXC and hassle 0.5.1 for intellisense (and vice-versa, need older DXC on 0.5.0 and below) has been documented.

Document `libdxcompiler` requirements for Linux and macOS; add `cargo-release` configuration

---

src/utils.rs

`BSTR` is a length-prefixed string type so that it can contain interior nul characters and other invalid or ill-formed UTF-16/UTF-32 data. Using that with a checked `WideCStr` is invalid however, which requires a single nul terminator at the end (conveniently `BSTR` includes a nul terminator beyond `SysStringLen`, but this is not part of the string itself); according to the docs ill-formed characters are still fine otherwise.
Use the "unchecked" `WideStr` type instead which allows interior nul values without affecting how the string is treated.
---
Was playing around with `widestring` yesterday and stumbled upon this `UStr`/`UCStr` convention. It's no big deal, likely never a problem IRL, but an easy fix nevertheless.

utils: Use unchecked widestring::WideStr for binary BSTR

---

examples/copy-over-56.hlsl
examples/copy-under-56.hlsl
examples/validate-fake-signing.rs
src/fake_sign/mod.rs
src/fake_sign/modified_md5.rs
src/lib.rs
src/utils.rs

This adds helper functions to sign dxil blobs without needing the `dxil.dll` present in the code repository. The code is a straight port from RenderDoc that has similar functionality.

🖖Add fake dxil signing support

---

src/utils.rs

Not all file loading should be fallible; DXC usually invokes the loader with multiple paths depending on relative includes, and happily accepts and expects us to return `-2_147_024_894 // ERROR_FILE_NOT_FOUND / 0x80070002` for some.  As such the precedent should be to not panic but let DXC decide if file loading failures should be critical or simply result in a different path being tested.
In my case though the error seems to originate from DXIL compilation being largely untested when ran on Linux systems through the WinAadapter codepath.  In this particular stacktrace below DXC seems to "stat" (get file information) for the current working directory, and somehow ends up trying to open the directory as file through our include handler:
#11 dxcutil::DxcArgsFileSystemImpl::TryFindOrOpen …

utils: Propagate IncludeHandler file loading failures to DXC instead of a panic

---

src/os.rs
src/utils.rs
src/wrapper.rs

Unify the use of `com_rs::HResult` into a newtyped `HRESULT` that allows us to place a `#[must_use]` annotation and in turn prevent missing errors from the API, which could lead to worse Undefined Behaviour.
In addition we can now use hexadecimal formatting for the `Display` and `Debug` traits making them much easier to read in `unwrap()` and similar scenarios.

os: Implement newtype for HRESULT with must_use and hexadecimal format

---

examples/intellisense-tu.rs
src/intellisense/wrapper.rs
src/lib.rs
src/utils.rs
src/wrapper.rs

Depends on #29
Our public API becomes a lot cleaner when returning `HassleError` everywhere, helped by the fact that `HRESULT`s from the low-level COM API is a newtype with support for functions to convert to `Result<>` easily.  These can be short-circuit-returned in a more Rust'y way through the questionmark operator instead of wrapping everything in large macro calls.  This change is based on a similar approach in the Ash crate: https://github.com/MaikKlein/ash/pull/339/files

Consistently return `HassleError` and remove unneeded check macros

---

examples/validate-fake-signing.rs
examples/validate.rs
src/fake_sign/mod.rs

The main reason for fake signing is making it run on Linux - and not depend on `dxil.dll` on Windows - so it's great if this example runs on Linux as well to see it all working even if that requires a few nasty cfg blocks.  Note that this is done with `cfg!()` and regular `if` blocks instead of attributes, such that this code lints and compiles on both Windows and Linux even if the `validate_dxil()` codepath is never entered on the latter (and that way includes, `let mut all_matches` etc don't need to be `#[cfg(windows)]`'ed out either).
---
Creating as draft because:
- This violates the `validate` name, but I think it's worth it being able to run this on Linux;
- ~Need to figure out why these shaders cause a `DefaultIncludeHandler::load_source()` for the root directory of this crate (it …

examples/fake-signing: Make runnable on Linux

---

.github/workflows/ci.yaml

There is not much point "preparing hassle-rs for the future" if the lints are false positives and prevent us from submitting or having actually good code.  Overnight two false positives got introduced: https://github.com/Traverse-Research/hassle-rs/runs/5006913943?check_suite_focus=true. One needs the borrow to satisfy a peculiar `From`/`Into` implementation, and the `&mut Vec<>` is pushed to which makes it impossible to turn this into a mutable borrow of a slice.

ci: Drop nightly build/lint tests

---

src/intellisense/wrapper.rs
src/os.rs
src/utils.rs
src/wrapper.rs

Depends on #26
Clean up casts to use `.cast()` to change the type while making it impossible to accidentally turn a `*const` into a `*mut`.
Also makes sure that the correct const-ness types, ie lpCstr and friends are used when the pointed-to data needs not to be modified: `*mut` coerces to `*const` (but for obvious reasons not the other way around).
Finally, fix the `CHAR` type to use `std::os::raw::c_char` which is defined to `u8` on Arm architectures and i8 on our x64 machines.

Use `.cast()` to not accidentally const_cast, fix Android char type

---

src/wrapper.rs

On Android - which is a Linux/Unix platform - the library path remains the same.

wrapper: Add Android library path

---

.github/workflows/ci.yaml

- ci: Remove mtime update hack; `clippy` now re-runs after `check`
- ci: Cache crate downloads and intermediates between runs

ci: Speed up by removing `touch` hack and caching intermediates

---

src/ffi.rs
src/wrapper.rs

The goal of this PR is to add the functionality of getting shader reflection from DXC.
The `ID3D12ShaderReflection` has been implemented in a very minimal way, as this interface is defined in libraries as `winapi` and `windows-rs`. The goal is to just build the object with the interface, and it's then up to the user what windows interface they want to use.

Implement basic wrapper for getting shader reflection from DXIL.

---

src/wrapper.rs

Fixes https://github.com/Traverse-Research/hassle-rs/issues/43

Rename macos library suffix from `dynlib` to `dylib`

---

src/fake_sign/mod.rs
src/wrapper.rs

Clippy gets more strict every Rust release, for good reasons!

Run `cargo clippy --fix` to address all (new) linter warnings

---

README.md
src/ffi.rs
src/intellisense/ffi.rs
src/lib.rs
src/wrapper.rs

This reverts commit c37cb037be072cac43f2706b89f1388b9deee19a. [This commit] is squashed in the merge of PR #5, and does not exist in-tree.
https://github.com/microsoft/DirectXShaderCompiler/pull/3793 has finally been merged on October 13th 2022 and now allows us to drop the vtable dummies for virtual destructors again, as those are not part of the ABI and shouldn't have been in the vtable in the first place.
[This commit]: https://github.com/Traverse-Research/hassle-rs/pull/5/commits/c37cb037be072cac43f2706b89f1388b9deee19a
---
Note that releasing `hassle-rs` with this change relies on a DXC built with at least that PR, which was meged on October 13th.

Breaking: Revert "[WIN/LINUX] Implement vtable dummies (virtual dtors) through extra trait"

---

.github/workflows/publish.yaml
release.toml

In this release workflow (already employed by other Traverse Research crates) `cargo-release` does the gruntwork and pushes a tag, but does publish to crates.io yet; this'll be done by the CI.
---
@Jasper-Bekkers can you also add https://crates.io/users/Traverse-Research-CI-runner to the owners of https://crates.io/crates/hassle-rs?  Otherwise this won't work :grimace:

github: Create publishing workflow on tag push, disable `cargo-release` publish

---

Cargo.toml

- cargo: Simplify `include` list
- Include MIT `LICENSE` file in release
- Release 0.10.0

Include MIT `LICENSE` file in packaged release

---

.github/workflows/ci.yaml

GitHub Actions' `runner-images` already come fully loaded with all the Rust tools that we need [1]: remove the bloated and outdated `actions-rs/toolchain` setup step for that, and also remove the `actions-rs/cargo` action that only serves as a more convoluted way to run simple `cargo` shell commands.
[1]: https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#rust-tools

CI: Replace unnecessary `actions-rs` steps with direct `run: cargo ...`

---

Cargo.toml

The only relevant change in v0.8 is the migration to `windows-sys`: https://docs.rs/libloading/0.8.0/libloading/changelog/r0_8_0/index.html.
This is done in the same spirit as https://github.com/gfx-rs/wgpu/pull/3711 because I heard Mozilla, who is using `wgpu`, isn't ready to migrate to `windows-sys` yet, see https://github.com/gfx-rs/wgpu/issues/3207.
`d3d12` did this as well: https://github.com/gfx-rs/d3d12-rs/pull/43.
Originally coming from here: https://github.com/Traverse-Research/hassle-rs/pull/67#discussion_r1222169498.

Allow `libloading` v0.7 and v0.8

---

src/wrapper.rs

Fixes #68, CC @expenses, please check if this fixes things for you!
There's no real reason to force `./` in default paths when the library is more and more likely to be installed on the system via `PATH` (on Windows it's in the Vulkan SDK, on Linux `directx-shader-compiler` is a common package).
Furthermore, stop appending this path to the optional `lib_path` argument, if that `lib_path` doesn't **exist** as a file.  In the case that a user specifies a (relative) path that doesn't exist, this throws an obscure error that `libdxcompiler.so/./libdxcompiler.so` doesn't exist because we appended a precooked filename a second time.

wrapper: Load libraries globally instead of relative to `$PWD`

---

src/utils.rs
src/wrapper.rs

Depends on #74. Based on conversation from #81.
Microsoft is providing `libdxil.so` for Linux for a while (and since [open-sourcing it](https://devblogs.microsoft.com/directx/open-sourcing-dxil-validator-hash/), users are able to compile `libdxil.dylib` for Mac as well). Allow `hassle-rs` to use it on every platform by removing the now-unnecessary `#[cfg(windows)]`.

Allow DXIL to be used outside of Windows as well

---

examples/include.rs
examples/spirv.rs
examples/validate-fake-signing.rs
examples/validate.rs
src/ffi.rs
src/lib.rs
src/os.rs
src/utils.rs
src/wrapper.rs

> [!TIP]
> This patch started 5 years ago when I was still learning Rust and not confident in how to best represent this complicated result status. I think I've found a convenient way now (that doesn't hide the available API too much) and finally got around to push this out.
Thus far `hassle-rs` has made it possible - but not very convenient - to extract warnings/errors from a `DxcOperationResult` together with an optional successful result-blob.  This was always eaten up by our high-level `utils` wrappers however, giving you either errors on failure or only the result blob on success, but never the warnings.  This was always only available when manually calling the high level `ffi` `wrapper`, with the same inconvenience that `utils` has.
There's barely any upstream documentation, but …

utils: Provide `OperationOutput` wrapper to parse `DxcOperationResult`

---

src/utils.rs

When just running with the latest error changes from PR #80, I was wondering why my error messages were disappearing but the `HRESULT` was printed twice (this is on runs with `-WX` to treat warnings as errors). Turns out I typo'd the `thiserror` format string to print the `HRESULT` in the second place as well rather than the error blob, resulting in: `Dxc error -80004005: -0x80004005`.  Replacing that with `{1}` gives the expected warning/error text from shader compilation again.

Fix missing error log in `HassleError::OperationError` `Display` format
